### PR TITLE
Mark played tracks in a multi-movement work as complete, and remove an unnecessary scope.

### PR DESCRIPTION
**Pull request by bbreslauer**

### CODE REVIEW

**Comment by adrianosbr** [comment]
Hi! Thank you so much for the PR. The multi-movement "slider" was originally intended to visually tell the listener which movement it's being played. If all previous tracks become yellow (i.e., "played"), it's somewhat harder to visualize which movement we're on. 

HOWEVER

The iOS version of Concertino, Concertmaster's sister app, behaves the way you intended. So I'm really not sure which way is better! :/

**Comment by bbreslauer** [comment]
Well, I think it does still show which movement is being played, because there are still vertical bars (with a movement number next to them) that show where the individual movements start and end. It looked weird (at least to me) to see a movement complete (with that part of the bar fully yellow) and then when the next movement starts the bar goes completely black and the next movement's part of the bar starts to become yellow. And I think it's a lot easier to visualize how much of a work you have listened to if all the past movements are yellow, because then it's just "how much of the bar is yellow", not "all the yellow, plus all the black to the left".

Also on a small screen (like a phone) it's very confusing currently, because there are no movement marks. So periodically, the bar goes from "a bit in the middle is yellow" to "it's all black" to "the next movement starts to be yellow". I think that unambiguously should either show the movement boundaries or have this commit (though, I have not actually tested this commit in a mobile view). And the movement boundaries would probably take up too much space on the small screen.

(I also saw in the Player Improvement project an entry "Make long multi-movement progress bars act like movement progress bar (all past highlighted, not only the current track)" that was "in production", so I figured this was just a bug :) )

**Comment by adrianosbr** [comment]
Now I'm fully convinced. I'll merge your PR :)

**Comment by adrianosbr** [comment]
It can be tested on the beta:

https://beta.concertmaster.app/

Two minor issues:

1. The new "full" progression bar doesn't work when we skip a track by clicking directly on another track;
2. It's affecting the individual progression bars (in the detail pane) and I'm not sure if they should behave like this.

I'll try to fix them later today (but feel free to deal with them).

Cheers!

**Comment by bbreslauer** [comment]
Oops, I'm still learning :)  I didn't even notice the detail view until you mentioned it. Regarding #2, in the detail pane, I think all the previous tracks should be marked complete.

I definitely will not be able to fix that right now, and I doubt I will today. But I can try and get to it at some point in the next week or so.

**Pull request merged**
